name: "Setup Dependencies"
description: "Setup language runtimes and common tools for a service"

inputs:
  service_path:
    description: "Path to service within the repository"
    required: true

  # Task
  install_task:
    description: "Install go-task"
    default: "true"
  task_version:
    description: "Version of task to install"
    default: "v3.44.0"

  # Language runtimes
  install_go:
    description: "Install Go"
    default: "false"
  install_node:
    description: "Install Node.js"
    default: "false"
  install_python:
    description: "Install Python"
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Install go-task
      if: ${{ inputs.install_task == 'true' }}
      uses: supplypike/setup-bin@1fafb085795af4a3f183502f3a9dffa8f7b83217
      with:
        uri: https://github.com/go-task/task/releases/download/${{ inputs.task_version }}/task_linux_amd64.tar.gz
        name: task
        version: ${{ inputs.task_version }}

    - name: Set up Go
      if: ${{ inputs.install_go == 'true' }}
      uses: actions/setup-go@1d76b952eb9246b03e20e15a9ef98c6d4af389ef
      with:
        go-version-file: ${{ inputs.service_path }}/go.mod
        cache-dependency-path: ${{ inputs.service_path }}/go.sum

    - name: Set up Node.js
      if: ${{ inputs.install_node == 'true' }}
      uses: actions/setup-node@d7a11313b581b306c961b506cfc8971208bb03f6
      with:
        node-version-file: ${{ inputs.service_path }}/package.json
        cache: npm
        cache-dependency-path: ${{ inputs.service_path }}/package-lock.json

    - name: Set up Poetry
      if: ${{ inputs.install_python == 'true' }}
      uses: snok/install-poetry@d526ede1e27960b7b181a5ac53044f552afdaa38

    - name: Set up Python
      if: ${{ inputs.install_python == 'true' }}
      uses: actions/setup-python@3d1e2d2ca0a067f27da6fec484fce7f5256def85
      with:
        python-version-file: ${{ inputs.service_path }}/pyproject.toml
        cache: poetry
        cache-dependency-path: ${{ inputs.service_path }}/poetry.lock
